package com.dh.spt.db.model;

// Generated 22 Nov, 2014 6:09:24 PM by Hibernate Tools 3.4.0.CR1

/**
 * ComplaintImages generated by hbm2java
 */
public class ComplaintImages implements java.io.Serializable {

	private Integer id;
	private Complaints complaints;
	private String imageName;
	private byte[] imageData;

	public ComplaintImages() {
	}

	public ComplaintImages(String imageName, byte[] imageData) {
		this.imageName = imageName;
		this.imageData = imageData;
	}

	public ComplaintImages(Complaints complaints, String imageName,
			byte[] imageData) {
		this.complaints = complaints;
		this.imageName = imageName;
		this.imageData = imageData;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Complaints getComplaints() {
		return this.complaints;
	}

	public void setComplaints(Complaints complaints) {
		this.complaints = complaints;
	}

	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	public byte[] getImageData() {
		return this.imageData;
	}

	public void setImageData(byte[] imageData) {
		this.imageData = imageData;
	}

}
